Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
display(mkImgsAnimateBox(dir="../images/imported_slides",
#                         force=True,
                         saveto="save1.html",
    files=['General_Presentation_1.jpg',
     'General_Presentation_2.jpg',
     'General_Presentation_3.jpg',
     'General_Presentation_4.jpg',
     'General_Presentation_5.jpg',
     'General_Presentation_6.jpg'
          ]))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[12], line 1[0m
[0;32m----> 1[0m display([43mmkImgsAnimateBox[49m[43m([49m[38;5;28;43mdir[39;49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m../images/imported_slides[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      2[0m [38;5;66;43;03m#                         force=True,[39;49;00m
[1;32m      3[0m [43m                         [49m[43msaveto[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43msave1.html[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      4[0m [43m    [49m[43mfiles[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mGeneral_Presentation_1.jpg[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      5[0m [43m     [49m[38;5;124;43m'[39;49m[38;5;124;43mGeneral_Presentation_2.jpg[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      6[0m [43m     [49m[38;5;124;43m'[39;49m[38;5;124;43mGeneral_Presentation_3.jpg[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      7[0m [43m     [49m[38;5;124;43m'[39;49m[38;5;124;43mGeneral_Presentation_4.jpg[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      8[0m [43m     [49m[38;5;124;43m'[39;49m[38;5;124;43mGeneral_Presentation_5.jpg[39;49m[38;5;124;43m'[39;49m[43m,[49m
[1;32m      9[0m [43m     [49m[38;5;124;43m'[39;49m[38;5;124;43mGeneral_Presentation_6.jpg[39;49m[38;5;124;43m'[39;49m
[1;32m     10[0m [43m          [49m[43m][49m[43m)[49m)

File [0;32m~/ope-docubook/content/python/common.py:139[0m, in [0;36mmkImgsAnimateBox[0;34m(dir, files, dpi, xpixels, ypixels, force, saveto)[0m
[1;32m    136[0m [38;5;28;01mif[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists([38;5;28mdir[39m [38;5;241m+[39m [38;5;124m"[39m[38;5;124m/[39m[38;5;124m"[39m [38;5;241m+[39m saveto):
[1;32m    137[0m     os[38;5;241m.[39mremove([38;5;28mdir[39m [38;5;241m+[39m [38;5;124m"[39m[38;5;124m/[39m[38;5;124m"[39m [38;5;241m+[39m saveto);
[0;32m--> 139[0m imgs[38;5;241m=[39m[43mfiles_to_imgArray[49m[43m([49m[38;5;28;43mdir[39;49m[43m,[49m[43m [49m[43mfiles[49m[43m)[49m
[1;32m    140[0m [38;5;28;01mif[39;00m (xpixels[38;5;241m==[39m[38;5;241m0[39m):
[1;32m    141[0m     xpixels [38;5;241m=[39m imgs[[38;5;241m0[39m][38;5;241m.[39mshape[[38;5;241m0[39m]

File [0;32m~/ope-docubook/content/python/common.py:117[0m, in [0;36mfiles_to_imgArray[0;34m(dir, files)[0m
[1;32m    115[0m imgs [38;5;241m=[39m [];
[1;32m    116[0m [38;5;28;01mfor[39;00m f [38;5;129;01min[39;00m files:
[0;32m--> 117[0m     imgs[38;5;241m.[39mappend([43mplt[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[38;5;28;43mdir[39;49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43m/[39;49m[38;5;124;43m"[39;49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[43mf[49m[43m)[49m)
[1;32m    118[0m [38;5;28;01mreturn[39;00m imgs

File [0;32m/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py:2195[0m, in [0;36mimread[0;34m(fname, format)[0m
[1;32m   2193[0m [38;5;129m@_copy_docstring_and_deprecators[39m(matplotlib[38;5;241m.[39mimage[38;5;241m.[39mimread)
[1;32m   2194[0m [38;5;28;01mdef[39;00m [38;5;21mimread[39m(fname, [38;5;28mformat[39m[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m-> 2195[0m     [38;5;28;01mreturn[39;00m [43mmatplotlib[49m[38;5;241;43m.[39;49m[43mimage[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[38;5;28;43mformat[39;49m[43m)[49m

File [0;32m/opt/conda/lib/python3.10/site-packages/matplotlib/image.py:1563[0m, in [0;36mimread[0;34m(fname, format)[0m
[1;32m   1556[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(fname, [38;5;28mstr[39m) [38;5;129;01mand[39;00m [38;5;28mlen[39m(parse[38;5;241m.[39murlparse(fname)[38;5;241m.[39mscheme) [38;5;241m>[39m [38;5;241m1[39m:
[1;32m   1557[0m     [38;5;66;03m# Pillow doesn't handle URLs directly.[39;00m
[1;32m   1558[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   1559[0m         [38;5;124m"[39m[38;5;124mPlease open the URL for reading and pass the [39m[38;5;124m"[39m
[1;32m   1560[0m         [38;5;124m"[39m[38;5;124mresult to Pillow, e.g. with [39m[38;5;124m"[39m
[1;32m   1561[0m         [38;5;124m"[39m[38;5;124m``np.array(PIL.Image.open(urllib.request.urlopen(url)))``.[39m[38;5;124m"[39m
[1;32m   1562[0m         )
[0;32m-> 1563[0m [38;5;28;01mwith[39;00m [43mimg_open[49m[43m([49m[43mfname[49m[43m)[49m [38;5;28;01mas[39;00m image:
[1;32m   1564[0m     [38;5;28;01mreturn[39;00m (_pil_png_to_float_array(image)
[1;32m   1565[0m             [38;5;28;01mif[39;00m [38;5;28misinstance[39m(image, PIL[38;5;241m.[39mPngImagePlugin[38;5;241m.[39mPngImageFile) [38;5;28;01melse[39;00m
[1;32m   1566[0m             pil_to_array(image))

File [0;32m/opt/conda/lib/python3.10/site-packages/PIL/Image.py:3236[0m, in [0;36mopen[0;34m(fp, mode, formats)[0m
[1;32m   3233[0m     filename [38;5;241m=[39m fp
[1;32m   3235[0m [38;5;28;01mif[39;00m filename:
[0;32m-> 3236[0m     fp [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m   3237[0m     exclusive_fp [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m   3239[0m [38;5;28;01mtry[39;00m:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../images/imported_slides/General_Presentation_1.jpg'
FileNotFoundError: [Errno 2] No such file or directory: '../images/imported_slides/General_Presentation_1.jpg'

